apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: newdecade-website-ingress
  namespace: newdecade
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  tls:
  - hosts:
    - newdecadeinsurance.com
    - www.newdecadeinsurance.com
    secretName: newdecade-production-tls
  rules:
  - host: newdecadeinsurance.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: newdecade-website-service
            port:
              number: 80
  - host: www.newdecadeinsurance.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: newdecade-website-service
            port:
              number: 80
